//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaterialAdvisor.QueueStorage.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MaterialAdvisor.QueueStorage.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answers count per each question: {0}..
        /// </summary>
        internal static string AnswersCountPrompt {
            get {
                return ResourceManager.GetString("AnswersCountPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complexity of questions should be approximately equal..
        /// </summary>
        internal static string EqualComplexityPrompt {
            get {
                return ResourceManager.GetString("EqualComplexityPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complexity of questions should be increased with its order number..
        /// </summary>
        internal static string IncreasingComplexityPrompt {
            get {
                return ResourceManager.GetString("IncreasingComplexityPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use next languages for all language related fields: {0}..
        /// </summary>
        internal static string LanguagesPrompt {
            get {
                return ResourceManager.GetString("LanguagesPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum questions count: {0}..
        /// </summary>
        internal static string MaxQuestionsCountPrompt {
            get {
                return ResourceManager.GetString("MaxQuestionsCountPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} questions of {1} type with {2} answer(s)&quot;.
        /// </summary>
        internal static string QuestionsSectionPrompt {
            get {
                return ResourceManager.GetString("QuestionsSectionPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use next questions structure: {0}..
        /// </summary>
        internal static string QuestionsStructurePrompt {
            get {
                return ResourceManager.GetString("QuestionsStructurePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use optimal answers count per each question..
        /// </summary>
        internal static string UseOptimalAnswersCountPrompt {
            get {
                return ResourceManager.GetString("UseOptimalAnswersCountPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use optimal questions count..
        /// </summary>
        internal static string UseOptimalQuestionsCountPrompt {
            get {
                return ResourceManager.GetString("UseOptimalQuestionsCountPrompt", resourceCulture);
            }
        }
    }
}
